name: Daily Commit

on:
  schedule:
   - cron: '35 18 * * *'  # Runs at 6:35 PM UTC (12:05 AM IST)
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 23f2001413@ds.study.iitm.ac.in
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "23f2001413@ds.study.iitm.ac.in"

      - name: Make a Dummy Commit
        run: |
          echo "Last run: $(date)" > last_run.txt
          git add last_run.txt
          git commit -m "Automated commit: $(date)"
          git push
